import { Inter } from "next/font/google";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Shreyans Mehta",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${inter.className} text-gray-950 bg-gray-50 relative`}>
        <div className="bg-[#fbe2be] -z-10 absolute top-[-6rem] right-[10rem] blur-[15rem] h-[49.1rem] w-[49.1rem] lg:w-[30rem] sm:w-[68.75rem] rounded-full"></div>
        <div className="bg-[#dbd7fb] -z-10 absolute top-[-1rem] left-[10rem] blur-[15rem] h-[49.1rem] md:w-[49.1rem] w-[12.75rem] rounded-full"></div>
        {children}
      </body>
    </html>
  );
}
