const Data = [
    {
        ProjectName:'Thursday Boots',
        ProjectDescription:'This project was made to make use of RESTAPI in Django',
        ProjectLink:'/NotFound',
        GithubLink:'https://github.com/mehtashreyans3602/ThursdayBoots',
        Technologies: ['django','sqlite','python'],
        Area:['BackEnd'],
    },
    {
    ProjectName:'Picstagram',
    ProjectDescription:'This project was made to demonstrate the functionalities of CRUD operation with django and sqlite by making a clone application of Instagram.',
    ProjectLink:'/NotFound',
    GithubLink:'https://github.com/mehtashreyans3602/Picstagram',
    Technologies: ['html','css','django','sqlite','pillow','python'],
    Area:['FullStack','FrontEnd','BackEnd'],
},

{
    ProjectName:'PU Navigation',
    ProjectDescription:'This project was made to make use of opensource mapbox maps platform. It consist of Typescript, Tailwind and Next.js',
    ProjectLink:'https://demopunav.vercel.app/',
    GithubLink:'https://github.com/mehtashreyans3602/PU-NAVIGATION',
    Technologies: ['react','next.js','appwrite'],
    Area:['FullStack','FrontEnd','BackEnd'],
},
{
    ProjectName:'DreamVault',
    ProjectDescription:'Here, I have built a Web3.0 Crowd Funding Application with FireChain and Next.js Typescript',
    ProjectLink:'https://dream-vault.vercel.app/',
    GithubLink:'https://github.com/mehtashreyans3602/DreamVault',
    Technologies: ['typescript','next.js','solidity'],
    Area:['FullStack','FrontEnd','BackEnd','Web3'],
},
{
    ProjectName:'spotifyclone',
    ProjectDescription:'Here, I made use of spotify api to replicate the user interface on a Next.js Web Application',
    ProjectLink:'https://spotifyclone-shreyans.vercel.app/',
    GithubLink:'https://github.com/mehtashreyans3602/spotifyclone',
    Technologies: ['javascript','next.js'],
    Area:['FullStack','FrontEnd'],
},
{
    ProjectName:'SEN-T-MENT',
    ProjectDescription:'Sentiment analysis on twitter tweets This is a web app made using Python and Flask Framework. Users can enter keywords to retrieve recent tweets based on the entered keyword, analyse their sentiment eg. Positive,negative or Neutral, and represent results through graphs.This project, used a popular “Tweepy” API. The Tweepy API creates a real-time connection with Twitter and collects text and metadata from the Twitter platform.',
    ProjectLink:'',
    GithubLink:'',
    Technologies: ['ML','Flask','Python'],
    Area:['MachineLearning'],
},
{
    ProjectName:'DuHacks FinTweet',
    ProjectDescription:'This is a Sentiment Analysis Project developed for the DuHacks Hackathon, is a web application which essentially takes statements from Users to perform Sentiment Analysis on them. The Web-App is made with flask framework for Back-end Development, a Convolutional Neural Network made from scratch with Keras,Tensorflow, sklearn, nltk which performs sentiment analysis and HTML, CSS and AJAX is used for the Front-End Development.',
    ProjectLink:'',
    GithubLink:'',
    Technologies: ['ML','Flask','Python'],
    Area:['MachineLearning'],
},
{
    ProjectName:'IBM DataScience Capestone Project',
    ProjectDescription:'This Project was part of Coursera IBM DataScience Professional Course Curriculum and Contains a series of mini Projects. The aim of this project was to perform all the steps as a DataScientist to predict the landing outcome of Falcon 9.',
    ProjectLink:'',
    GithubLink:'',
    Technologies: ['ML','DataScience','Python','WebScraping'],
    Area:['MachineLearning'],
},
{
    ProjectName:'Agrem Technosol',
    ProjectDescription:'This Website was developed as an Freelancing Project to Redesign the Website of the same company which was later terminated.',
    ProjectLink:'',
    GithubLink:'',
    Technologies: ['javascript','next.js','mysql'],
    Area:['FullStack','FrontEnd','BackEnd'],
},
];
export default Data;